name: pytelpoint
channels:
  - conda-forge
dependencies:
  - python>=3.13
  - astropy
  - scipy
  - matplotlib
  - numpy
  - pandas
  - arviz
  - corner
  - pymc
  - pip
  - ipympl
  - ipykernel
  - coverage
  - pytest-astropy
  - black
  - flake8
  - pytest-benchmark
  - sphinx-astropy
  - pip:
    - tox
    - tox-conda
